source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'waterReportApp' do
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Charts'
end
